wget https://github.com/MCSManager/PTY/releases/download/latest/pty_darwin_arm64
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_darwin_x64
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_freebsd_386
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_freebsd_arm
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_freebsd_arm64
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_freebsd_x64
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_linux_386
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_linux_arm
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_linux_arm64
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_linux_mips
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_linux_mips64
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_linux_mips64le
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_linux_mipsle
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_linux_ppc64
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_linux_ppc64le
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_linux_riscv64
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_linux_s390x
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_linux_x64
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_netbsd_386
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_netbsd_arm
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_netbsd_arm64
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_netbsd_x64
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_openbsd_386
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_openbsd_arm
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_openbsd_arm64
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_openbsd_x64
wget https://github.com/MCSManager/PTY/releases/download/latest/pty_win32_x64.exe
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/7z-extra-license.txt
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/7z-unix-license.txt
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/7z_darwin_arm64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/7z_darwin_x64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/7z_linux_386
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/7z_linux_arm
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/7z_linux_arm64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/7z_linux_x64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/7z_win32_arm64.exe
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/7z_win32_x64.exe
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_darwin_amd64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_darwin_arm64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_freebsd_386
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_freebsd_arm
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_freebsd_arm64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_freebsd_x64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_linux_386
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_linux_arm
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_linux_arm64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_linux_mips
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_linux_mips64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_linux_mipsle
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_linux_ppc64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_linux_riscv64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_linux_s390x
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_linux_x64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_netbsd_arm
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_netbsd_arm64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_netbsd_x64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_openbsd_386
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_openbsd_arm
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_openbsd_arm64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_openbsd_x64
wget https://github.com/MCSManager/Zip-Tools/releases/download/v1.0.1/file_zip_win32_x64.exe

